name: photos from spain
favicon: null
layout_spectrum: 0.5963039041962475
typography_spectrum: 0.85884
title: Photos from Three Weeks in Spain
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#847c4d'
    - '#d2d5c4'
    - '#860000'
    - '#bf470e'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
